#ifndef EDITERAKO_LOGGING_H
#define EDITERAKO_LOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcCore)
Q_DECLARE_LOGGING_CATEGORY(lcEditor)
Q_DECLARE_LOGGING_CATEGORY(lcSyntax)
Q_DECLARE_LOGGING_CATEGORY(lcProject)
Q_DECLARE_LOGGING_CATEGORY(lcTerminal)
Q_DECLARE_LOGGING_CATEGORY(lcAi)
Q_DECLARE_LOGGING_CATEGORY(lcViewer)
Q_DECLARE_LOGGING_CATEGORY(lcLsp)
Q_DECLARE_LOGGING_CATEGORY(lcScm)
Q_DECLARE_LOGGING_CATEGORY(lcTasks)

#endif
