(comment) @comment
(identifier) @variable
(literal) @string
(numeric) @number
(keyword_select) @keyword
(keyword_from) @keyword
(keyword_where) @keyword
(keyword_insert) @keyword
(keyword_into) @keyword
(keyword_update) @keyword
(keyword_delete) @keyword
(keyword_create) @keyword
(keyword_table) @keyword
(keyword_and) @keyword
(keyword_or) @keyword
(keyword_not) @keyword
(keyword_as) @keyword
(keyword_join) @keyword
(keyword_on) @keyword
(keyword_values) @keyword
